### ISSUE TITLE
Dictionary attach stops mid-dic outputing single word to console

### ISSUE THREAD

**Issue by andrewtch** [hyc/fcrackzip#9]
Subk:

```
root@:~# fcrackzip --verbose --use-unzip --dictionary --init-password  ~/SecLists/Passwords/darkc0de.txt ~/password.zip
found file 'file.txt', (size cp/uc 6845944/6853040, flags 9, chk 75aa)
root@:~# eonian
```

There is no "eonian" word in darkc0de.txt, just "Meonian" which is around ~59% of file.

What is happening?

**Comment by aapo** [comment]
zipcrack.c:70

       if (++crack_count >= 1000000 && verbosity)
         {
           printf ("checking pw %-40.40s\r", pw), fflush (stdout);

Because **--verbose** it will print "checking pw ..." without newline (\n) but just carriage return (\r). If password was not found in the dictionary it will not print anything more, not even newline. Then program ends and your shell prints it's own prompt. Because verbose is not printing every guess you will not see the last word in the dictionary.

If you want that ending of the program prints something and that prompt is on own row:
   
    diff --git a/main.c b/main.c
    index 8e1bf5b..8981329 100644
    --- a/main.c
    +++ b/main.c
    @@ -578,5 +578,8 @@ main (int argc, char *argv[])
           exit (1);
         }
     
    +
    +  printf("\nNot found\n");
    +
       return 0;
     }
